[package]
name = "pf_application"
version = "0.1.0"
edition = "2021"

[dependencies]

tokio = { version = "1.38.0", features = ["full"] }
eyre = "0.6"
ethers = { git = "https://github.com/gakonst/ethers-rs" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.120"
